---
- hosts: all
  user: vagrant
  tasks:
    - name: yum update
      yum: name=* state=latest
      sudo: yes
    - name: install development tools
      yum: name="@Development tools"
      sudo: yes
    - name: install packages
      yum: name={{ item }}
      sudo: yes
      with_items:
        - git
        - mercurial
        - tmux
        - emacs
        - memcached
        - java-1.7.0-openjdk
        - yum-utils
    - name: install mysql yum repository
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present
      sudo: yes
    - name: disable mysql57-community repository
      command: yum-config-manager --disable mysql57-community
      sudo: yes
    - name: enable mysql56-community repository
      command: yum-config-manager --enable mysql56-community
      sudo: yes
    - name: install mysql stuff
      yum: name={{ item }}
      sudo: yes
      with_items:
        - mysql-community-libs
        - mysql-community-server
        - mysql-community-devel
    - name: install linuxbrew deps
      yum: name={{ item }}
      sudo: yes
      with_items:
        - curl
        - git
        - irb
        - m4
        - python-setuptools
        - ruby
        - texinfo
        - bzip2-devel
        - curl-devel
        - expat-devel
        - ncurses-devel
        - zlib-devel
    - name: install linuxbrew
      git: repo=https://github.com/Homebrew/linuxbrew.git dest=~/.linuxbrew
