---
- hosts: all
  user: vagrant
  tasks:
    - name: yum update
      yum: name=* state=latest
      sudo: yes
    - name: install development tools
      yum: name="@Development tools"
      sudo: yes
    - name: install packages
      yum: name={{ item }}
      sudo: yes
      with_items:
        - git
        - mercurial
        - tmux
        - emacs
        - memcached
        - java-1.7.0-openjdk
        - yum-utils
    - name: install mysql yum repository
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present
      sudo: yes
    - name: disable mysql57-community repository
      command: yum-config-manager --disable mysql57-community
      sudo: yes
    - name: enable mysql56-community repository
      command: yum-config-manager --enable mysql56-community
      sudo: yes
    - name: install mysql stuff
      yum: name={{ item }}
      sudo: yes
      with_items:
        - mysql-community-libs
        - mysql-community-server
        - mysql-community-devel
    - name: install linuxbrew deps
      yum: name={{ item }}
      sudo: yes
      with_items:
        - curl
        - git
        - irb
        - m4
        - python-setuptools
        - ruby
        - texinfo
        - bzip2-devel
        - curl-devel
        - expat-devel
        - ncurses-devel
        - zlib-devel
    - name: install linuxbrew
      git: repo=https://github.com/Homebrew/linuxbrew.git dest=~/.linuxbrew
    - name: install rvm, gpg stuff
      command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - name: install rvm, get rvm installer
      get_url: url=https://get.rvm.io dest=~/rvm-installer mode=0755
    - name: install rvm, run installer
      command: ~/rvm-installer
